config/routes.rb
Rails.application.routes.draw do
  resources :products do
    collection do
      post "sort",to: "products#sort"
    end
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :sub_products #,  inverse_of: :product, dependent: :destroy
  accepts_nested_attributes_for :sub_products, allow_destroy: true, reject_if: :all_blank

  # scope :desc, order("events.event_at DESC")
  scope :cheapest,    -> { order(price: :asc) }
  scope :expensive,   -> { order(price: :desc) }
  scope :newest,   -> { order(created_at: :desc) }

  validates_presence_of :name, :price
  validates :price, numericality: {only_integer: true}
end

app/models/sub_product.rb
class SubProduct < ApplicationRecord
  belongs_to :product, inverse_of: :sub_products
  validates_presence_of :name, :price
  validates :price, :numericality => {:only_integer => true}

  scope :cheapest,    -> { sort {|a, b| a.price <=> b.price} }
  scope :expensive,   -> { sort {|a, b| b.price <=> a.price} }
  scope :newest,   -> { sort {|a, b| b.created_at <=> a.created_at} }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  skip_before_action :verify_authenticity_token
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[ show edit update destroy ]

  # GET /products or /products.json
  def index
    @products = Product.newest
    respond_to do |format|
      format.html
      format.pdf do
        render page_size: 'A4',
               template: "products/index.html.erb",
               layout: "pdf.html",
               orientation: "Landscape",
               lowquality: true,
               zoom: 1,
               dpi: 75
      end
    end
  end

  # GET /products/1 or /products/1.json
  def show
    respond_to do |format|
      format.html
      format.pdf do
        render pdf: "Invoice No. #{@product.id}",
               page_size: 'A4',
               template: "products/show.html.erb",
               layout: "pdf.html",
               orientation: "Landscape",
               lowquality: true,
               zoom: 1,
               dpi: 75
      end
    end
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products or /products.json
  def create
    @product = Product.new(product_params)
    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: "Product was successfully created." }
        format.json { render :show, status: :created, location: @products }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: "Product was successfully updated." }
        format.json { render :show, status: :ok, location: @products }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: "Product was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def sort
    @order = params[:sort_by]
    if @order.eql?('Cheapest')
      @products = Product.cheapest
    elsif @order.eql?('Expensive')
       @products = Product.expensive
    else
      @products = Product.newest
    end
    respond_to do |format|
        format.js
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:name, :price, :check_value, sub_products_attributes: [:id, :name, :price, :check_value, :_destroy])
    end

end

app/controllers/sub_products_controller.rb
class SubProductsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper

  # def link_to_add_fields(name, f, association)
  #   new_object = f.object.send(association).klass.new
  #   id = new_object.object_id
  #   fields = f.fields_for(association, new_object, child_index: id) do |builder|
  #     render(association.to_s.singularize + "_fields", f: builder)
  #   end
  #   link_to(name, '#', class: "add_fields", data: {id: id, fields: fields.gsub("\n", "")})
  # end

end

app/helpers/products_helper.rb
module ProductsHelper

  def link_to_add_fields(name, f, association)
    new_object = f.object.send(association).klass.new
    id = new_object.object_id
    fields = f.fields_for(association, new_object, child_index: id) do |builder|
      render("#{association.to_s.singularize}_fields", form: builder)
    end
    link_to(name, '#', class: "add_fields", data: {id: id, fields: fields.gsub("\n", "")})
  end

end

app/helpers/sub_products_helper.rb
module SubProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EcommerceStore</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/pdf.html.erb
# file: rails-generate-pdf/views/layotus/pdf.html.erb

<html>
<head>
  <title>PDFs - Ruby on Rails</title>
  <%= wicked_pdf_stylesheet_link_tag "invoice" %>
</head>
<body>
<%= yield %>
</body>
</html>

app/views/products/_form.html.erb
<%= form_with model: product, local: true do |form| %>
  <%= form.label :name %>
  <%= form.text_field :name %>
  <%= form.label :price %>
  <%= form.text_field :price %>
  <fieldset>
    <legend>SubProducts:</legend>
    <%= form.fields_for :sub_products do |sub_product| %>
      <%= render "products/sub_product_fields", formats: [:html], form: sub_product %><br>
    <% end %><br>
<!--    <p><%#= form.link_to_add "Add a task", :sub_products %></p>-->
    <%= link_to_add_fields "Add Sub-Products", form, :sub_products %>
  </fieldset>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/products/_product_list.html.erb
<% @products.each do |product| %>
  <%= hidden_field_tag("product_value_#{product.id}", product.price.to_f) %>
  <tr>
    <td><%= check_box_tag("product_#{product.id}", value = "1", checked = false, options = {}) %></td>
    <td><%= product.name %></td>
    <td><%= product.price %></td>
    <td colspan="2"></td>
    <td>
      <table>
        <tr></tr>
        <tr>
          <th></th>
          <th>Name</th>
          <th></th>
          <th>Price</th>
        </tr>
        <% product.sub_products.each do |sub_product| %>
          <tr></tr>
          <tr>
            <td><%= check_box_tag("sub_product_#{product.id}", value = "1", checked = false, options = {}) %></td>
            <td><%= sub_product.name %></td>
            <td></td>
            <td><%= sub_product.price %></td>
          </tr>
        <% end %>
      </table>
    </td>
    <td></td>
    <td><%= link_to 'Edit', edit_product_path(product) %></td>
    <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td><br>
  </tr>

<script>
    $('#product_<%= product.id %>').change(function() {
        alert('in'+$(this).is(":checked"));
       if($(this).is(":checked")){
           $(this).prop('checked', true);
           if ("<% product.sub_products.present? %>"){
               $('#sub_product_<%= product.id %>').prop('checked', true);
           }
           $("#total_price").html(Number($("#total_price").html()) + <%= product.price.to_f %>);
       } else {
           $('#sub_product_<%= product.id %>').prop('checked', false);
           $("#total_price").html(Number($("#total_price").html()) - <%= product.price.to_f %>);
       }
    });
</script>
<% end %>

app/views/products/_sub_product_fields.html.erb
<div class="nested-fields">
  <%= form.hidden_field :_destroy %>
  <div>
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>
  <div>
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>
  <div>
    <%= link_to "Remove", '#', class: "remove_fields" %>
  </div>
</div>

app/views/products/edit.html.erb
<h1>Editing Product</h1>
<%= render 'form', product: @product %>
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<p id="notice"><%= notice %></p>
<h1>Products</h1>
<%#= link_to ‘DOWNLOAD PDF’, product_path(format: :pdf) %>
<%= select_tag 'order', options_for_select(%w[Newest Cheapest Expensive], :selected => @order) %>

<table>
  <thead>
  <tr>
    <th>Product</th>
    <th>Name</th>
    <th>Price</th>
    <th colspan="2"></th>
    <th>Sub Product</th>
    <th></th>
    <th colspan="2">Actions</th>
  </tr>
  </thead>

  <tbody id="product_list">
  <%= render "products/product_list" %>
  </tbody>
</table>
<div>
  <div><b>Sum:</b> <span id="sum" >1121</span></div>
  <div><b>VAT:</b> <span id="vat">17.5%</span><br></div>
  <div><b>Total Price:</b> <span id = "total_price"/></div>
</div>
<br>
<%= link_to 'New Product', new_product_path %>

<script>
    jQuery(document).ready(function() {
        let sum = document.getElementById("sum").innerText;
        if (sum == 0){
            document.getElementById("total_price").innerText = '0';
        }else{
            let sum = document.getElementById("sum").innerText;
            let vat_total = 0;
            if (sum != 0){
                let diff = sum / 117.5;
                let result = 0;
                if (diff != 17.5) {
                    result = (diff + 100) / diff;
                }else {
                    result = diff;
                }
                let pre_vat_total = result * 100
                vat_total = result * 17.5;
            }
            document.getElementById("total_price").innerText = parseFloat(vat_total).toFixed(3);
        }
    });

    $('#order').on('change', function() {
        $.post({
            url: '/products/sort',
            data: {sort_by: $(this).val()},
            success: function (data) {
                $("#product_list").html(data);
                $("#total_price").html("0");
            },
            error: function (error) {
                console.log('Error ' + error);
            },
        });
    })

</script>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>

app/views/products/sort.html.erb
<%= render partial: 'products/product_list' %>

app/views/sub_products/_form.html.erb
<%= form_with model: :sub_product, local: true do |form| %>
  <%= form.label :name %>
  <%= form.text_field :name %>
  <%= form.label :price %>
  <%= form.text_field :price %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/sub_products/edit.html.erb
<h1>Editing Sub Product</h1>

<%= render 'form', sub_product: :sub_product %>

<%= link_to 'Back', products_path %>

app/views/sub_products/new.html.erb
<h1>New Sub Product</h1>

<%= render 'form', product: :sub_product %>

<%= link_to 'Back', products_path %>